name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: "Install dependencies"
      run: python3 -m pip install build
    - name: "Build package"
      run: python3 -m build
    - uses: pypa/gh-action-pypi-publish@v1.8.1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
